# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*
pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Integration_Build
    displayName: Integration Build
    jobs:
      - job:
        steps:
          - task: gitversion/setup@0
            displayName: Setup GitVersion
            inputs:
              versionSpec: 5.x
          - task: gitversion/execute@0
            displayName: Execute GitVersion
          - task: NodeTool@0
            displayName: Setup Node.js
            inputs:
              versionSpec: 14.x
          - task: Bash@3
            displayName: Compile Extension Assembly
            inputs:
              script: 'sbt -J-Xmx4G -J-Xms2G package'
              targetType: 'inline'
          - task: TfxInstaller@3
            displayName: Setup tfx-cli Tool
            inputs:
              version: 'v0.9.x'
          - task: PackageAzureDevOpsExtension@3
            displayName: Package DevOps Extension
            inputs:
              extensionVersion: $(GitVersion.SemVer)
              updateTasksVersion: false
              rootFolder: 'target/vsix'

  - ${{ if startsWith(variables[ 'Build.SourceBranch' ], 'refs/tags/v') }}:
      - stage: Publish_Tagged_Extension
        displayName: Publish Tagged Extension
        dependsOn: Integration_Build
        jobs:
          - job:
            steps:
              - task: gitversion/setup@0
                displayName: Setup GitVersion
                inputs:
                  versionSpec: '5.x'
              - task: gitversion/execute@0
                displayName: Execute GitVersion
              - task: NodeTool@0
                displayName: Setup Node.js
                inputs:
                  versionSpec: '14.x'
              - task: Bash@3
                displayName: Compile Extension Assembly
                inputs:
                  script: 'sbt -J-Xmx4G -J-Xms2G package'
                  targetType: 'inline'
              - task: TfxInstaller@3
                displayName: Setup tfx-cli Tool
                inputs:
                  version: 'v0.9.x'
              - task: PackageAzureDevOpsExtension@3
                displayName: Package DevOps Extension
                inputs:
                  extensionVersion: $(GitVersion.SemVer)
                  updateTasksVersion: false
                  rootFolder: 'target/vsix'
              - task: PublishAzureDevOpsExtension@3
                displayName: Publish DevOps Extension
                condition: and(succeeded(), not(contains(variables['GitVersion.SemVer'], '-')), not(contains(variables['GitVersion.SemVer'], '+')))
                inputs:
                  connectTo: 'VsTeam'
                  connectedServiceName: 'vsts-marketplace'
                  fileType: 'vsix'
                  vsixFile: 'duchessa.pipelines4s*.vsix'
